language: java
sudo: false

jdk:
  - oraclejdk7

env:
  global:
    - MAVEN_OPTS="-Djna.library.path=${TRAVIS_BUILD_DIR}/travis -DskipTests=false -DfailIfNoTests=false"

before_install:
  - ip addr show
  - hostname -I
  - curl -v http://thredds-test.unidata.ucar.edu/thredds/catalog.xml
  - curl -v http://thredds-dev.unidata.ucar.edu/thredds/catalog.xml
  - curl -v http://thredds.ucar.edu/thredds/catalog.xml
  - curl -v http://atm.ucar.edu/thredds/catalog.xml

install:
  - mvn install -DskipTests=true

script:
  - cd cdm && mvn test ${MAVEN_OPTS}

cache:
  directories:
    - $HOME/.m2
