language: java
sudo: false

jdk:
  - oraclejdk7

env:
  global:
    - MAVEN_OPTS="-Djna.library.path=${TRAVIS_BUILD_DIR}/travis -DskipTests=false -DfailIfNoTests=false"

before_install:
  - echo GET / | nc -vvv thredds.ucar.edu 80
  - curl -v http://thredds-test.unidata.ucar.edu/thredds/catalog.xml
  - curl -v http://thredds-dev.unidata.ucar.edu/thredds/catalog.xml
  - curl -v http://comet.ucar.edu
  - curl -v http://unidata2-new.ssec.wisc.edu/thredds/catalog.xml
  - curl -v http://atm.ucar.edu
  - curl -v http://threddsRC.ucar.edu
  - curl -v http://threddsBackup.ucar.edu
    #- curl -v https://thredds.ucar.edu
  - curl -v http://thredds.ucar.edu
  - curl -v http://thredds.ucar.edu/thredds/catalog.xml
  - curl -v http://atm.ucar.edu/thredds/catalog.xml

install:
  - mvn install -DskipTests=true

script:
  - cd cdm && mvn test ${MAVEN_OPTS}

cache:
  directories:
    - $HOME/.m2
